language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6"

sudo: false

# Command to install dependencies
install: "pip install --upgrade -r requirements/travis.txt"

# Command to setup Django, database, and run tests
script:
  - (cd inventory/settings/; ln -s travis.py local.py)
  - python manage.py makemigrations accounts categories invoices locations projects regions suppliers
  - python manage.py migrate
  - make coverage

after_success:
  - coveralls 
