language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

before_script:
  - psql -U postgres template1 -f db/create_schema.ddl

# Command to install dependencies
install: "pip install --upgrade -r requirements/travis.txt"

# Command to setup Django, database, and run tests
script:
  - (cd inventory/settings/; ln -s travis.py local.py)
  - python manage.py makemigrations accounts categories invoices locations projects regions suppliers
  - python manage.py migrate
  - make tests TEST_ARGS=--parallel=1

after_success:
  - coveralls 
